# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    tags:
    - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Download image builder
        run: |
          sudo apt update
          sudo apt install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-setuptools rsync swig unzip zlib1g-dev file wget
          wget https://downloads.openwrt.org/releases/23.05.3/targets/ramips/mt7621/openwrt-imagebuilder-23.05.3-ramips-mt7621.Linux-x86_64.tar.xz
          tar xf openwrt-imagebuilder-23.05.3-ramips-mt7621.Linux-x86_64.tar.xz

      # Runs a set of commands using the runners shell
      - name: Build the custom image
        run: |
          cd openwrt-imagebuilder-23.05.3-ramips-mt7621.Linux-x86_64/
          PACKAGES=""
          while read -r line; do
            PACKAGES="${PACKAGES} ${line}"
          done < ../packages
          make image PROFILE="thunder_timecloud" PACKAGES="$PACKAGES"
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          # Artifact name
          name: openwrt-ramips-mt7621-thunder_timecloud-squashfs-sysupgrade.bin
          # A file, directory or wildcard pattern that describes what to upload
          path: openwrt-imagebuilder-23.05.3-ramips-mt7621.Linux-x86_64/bin/targets/ramips/mt7621/openwrt-23.05.3-ramips-mt7621-thunder_timecloud-squashfs-sysupgrade.bin
          # The desired behavior if no files are found using the provided path.
      
      - name: Auto Release
        uses: CupOfTea696/gh-action-auto-release@v1.0.0
        with:
          title: "Release: $version"
          tag: "v$semver"
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

